name: CI-CD-workFlow

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: hassansheikh993
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Backend
        run: |
          docker build -t hassansheikh993/merin_backend:latest ./server
          docker push hassansheikh993/merin_backend:latest

      - name: Build and Push Frontend
        run: |
          docker build -t hassansheikh993/merin_frontend:latest ./front_end/vite-project
          docker push hassansheikh993/merin_frontend:latest

  
